### ISSUE TITLE
Swift package support

### ISSUE THREAD

**Issue by aidansteele** [nst/BinUtils#1]
Hi,

I love your project - looks very useful! Would you be open to a PR that makes this project into a [Swift Package Manager](https://github.com/apple/swift-package-manager)-compatible package? This would make it easier for me (and presumably others) to integrate your work into our projects. If yes, I would be happy to do the work.

**Comment by nst** [comment]
Hello, of course I'd agree to make the file available through SPM, I just never took time to do so and I don't know how it works.

**Comment by aidansteele** [comment]
Great! I'll submit a PR very soon and include some information in that. :)

**Comment by aidansteele** [comment]
Closing issue in favour of continuing discussion in the PR #2.
